apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-warehouse
  namespace: my-warehouse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - my-warehouse.example.com
      secretName: my-warehouse-tls
  rules:
    - host: my-warehouse.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-warehouse-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-warehouse-frontend
                port:
                  number: 80
